name: Document
on: [push, pull_request]
jobs:
  all:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: hecrj/setup-rust-action@v2
      with:
        rust-version: nightly-2026-02-20
    - uses: actions/checkout@v2
    - name: Generate documentation
      run: |
        RUSTDOCFLAGS="--cfg docsrs" \
          cargo doc --no-deps --all-features \
          -p futures-core \
          -p enative_beacon \
          -p enative_core \
          -p enative_debug \
          -p enative_devtools \
          -p enative_futures \
          -p enative_graphics \
          -p enative_highlighter \
          -p enative_renderer \
          -p enative_runtime \
          -p enative_tiny_skia \
          -p enative_wgpu \
          -p enative_widget \
          -p enative_winit \
          -p enative_test \
          -p enative
    - name: Write CNAME file
      run: echo 'docs.enative.rs' > ./target/doc/CNAME
    - name: Copy redirect file as index.html
      run: cp docs/redirect.html target/doc/index.html
    - name: Publish documentation
      if: github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
        external_repository: enative-rs/docs
        publish_dir: ./target/doc
